### ISSUE TITLE
u should add a tutorial how to use it!

### ISSUE THREAD

**Issue by gilbertobitt** [vandernorth/NecroBot.GUI#1]

**Comment by Ubiquitous-X** [comment]
+1 A compiled exe would be nice!

**Comment by vandernorth** [comment]
Its on my to do list. Probably tomorrow.

**Comment by vandernorth** [comment]
Ok, there is a zip in the latest release: https://github.com/vandernorth/NecroBot.GUI/releases/tag/v0.3.1

Download it, unzip all of it and change the auth.json and config.json to suit your needs.
