### ISSUE TITLE
Separate from Necrobot?

### ISSUE THREAD

**Issue by kbtbc** [vandernorth/NecroBot.GUI#10]
What version of necrobot is under the hood?   How will it keep in sync as new versions of necrobot are released? 
Is it possible to have your GUI standalone and get the info via necrobots:   "UseWebsocket": true?

**Comment by vandernorth** [comment]
Under the hood is v0..8.5 and can easily be upgraded to newer versions (I have done so since necrobot v0.3.x) 

Add this moment it is not possible to use the websocket connection to the CLI version of necrobot. Its not on the planning.
