### ISSUE TITLE
Egg hatching error

### ISSUE THREAD

**Issue by mmanlapat** [vandernorth/NecroBot.GUI#100]
### Issue or feature request?
ISSUE

### Expected Behavior
Egg hatching correctly

### Actual Behavior
Egg giving error message
![asdas](https://cloud.githubusercontent.com/assets/5326695/17768604/420402a8-6567-11e6-806d-6c5dcfb49695.JPG)

### Steps to Reproduce
Hatch an egg

### Other Information
Version: 0.5.0
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): egg

**Comment by vandernorth** [comment]
this if for the bot core, please raise an issue there..
