### ISSUE TITLE
GUI Just Closes

### ISSUE THREAD

**Issue by tmathura** [vandernorth/NecroBot.GUI#102]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Issue or feature request?
... Issue

### Expected Behavior
... Expect the gui to stay open till I close it. I have include my config and latest log

[log.txt](https://github.com/vandernorth/NecroBot.GUI/files/424589/log.txt)
[config.txt](https://github.com/vandernorth/NecroBot.GUI/files/424590/config.txt)

### Actual Behavior
... gui closes by itself

### Steps to Reproduce
... open and leave running for over an hour or more

### Other Information
Version: 0.5.0
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by tmathura** [comment]
I am guessing it's related to the UseKillSwitchCatch in the config?

**Comment by vandernorth** [comment]
See #104
