### ISSUE TITLE
LVL problem

### ISSUE THREAD

**Issue by Astifleure** [vandernorth/NecroBot.GUI#103]
Hi, any idea why the bot dont load my real profil, he say i'm lvl 1 with no pokemon instead of lvl 19 with too much...

**Comment by RuneMykle** [comment]
Your Config/auth.json fil defines your user.

So check this file and set correct username and password and you are good to go.

**Comment by Astifleure** [comment]
i've ever enter the good ID and PASSW, i have the same with normal necrobot and it work perfectly...

**Comment by vandernorth** [comment]
I don't know... I don't 'make up' these values, they really come from the server....

**Comment by Wise01** [comment]
If you use ptc, make sure "GoogleUsername"and "GooglePassword" are set to null.
If you use google make sure "PtcUsername" and "PtcPassword" are set to null.
Hopefully it helps.
