### ISSUE TITLE
[Request] Saving columns setup in the workspace xml file

### ISSUE THREAD

**Issue by Wise01** [vandernorth/NecroBot.GUI#107]
### Issue or feature request?

Request
### Expected Behavior

Would be cool if the xml file could save the columns size and position.
### Actual Behavior

I believe it works as intended
### Steps to Reproduce

...
### Other Information

Version: 0.5.0
Windows Version: 10 64bits (Does it matter tho?)
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): Time to setup the bot each time I start it :laughing: 

So I love to be able to save/load the workspace it saves a lot of time but I still take some time to setup the columns in the Pokemon tab because I don't care much about the Pokemon ID or catch date. I usually set it up like this:

![screen shot 08-18-16 at 05 09 pm](https://cloud.githubusercontent.com/assets/21106202/17779244/3d18be46-6567-11e6-97ee-e5ebf027a176.PNG)

It is not really important but it would be cool.

**Comment by czokalapik** [comment]
I second that!
