### ISSUE TITLE
Favorite not working

### ISSUE THREAD

**Issue by sevenzsu** [vandernorth/NecroBot.GUI#108]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Issue or feature request?
Issue

### Expected Behavior
(un)Favorite from context menu

### Actual Behavior
Error: new name is empty, not setting it

### Steps to Reproduce
right click and favorite

### Other Information
Version: 0.5.0
Windows Version:
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by czokalapik** [comment]
Same issue
