### ISSUE TITLE
cannot run, always close

### ISSUE THREAD

**Issue by hanncreator** [vandernorth/NecroBot.GUI#109]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Issue or feature request?
Can you help me? When opening gui.exe straight away without any notice problems .
Auth.json already set dah .net framework is up to date
### Expected Behavior
...

### Actual Behavior
...

### Steps to Reproduce
...

### Other Information
Version:0.5.0
Windows Version: 7
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by thosuperman** [comment]
Can you try to login on your Pokemon App. Maybe your account got permanent banned so it can't run.

**Comment by golgolak** [comment]
there's a logs folder, check the dump. also when it starts look at the bottom left corner of the GUI, it shows the error it encountered before closing down.

not sure if needed for the gui version of noxx... you may want to install this
https://www.microsoft.com/en-US/download/details.aspx?id=48145

**Comment by vandernorth** [comment]
See #104
