### ISSUE TITLE
Wont run

### ISSUE THREAD

**Issue by RuneMykle** [vandernorth/NecroBot.GUI#11]
Same config and auth that ran fine in prev version.

Tried to run this first time as admin as suggested to improve map features.

Gui never appears on 0.3.2, but works fine on 0.3.1.

**Comment by RuneMykle** [comment]
Logfile says:

> Initializing NecroBot logger at time 11.08.2016 23.01.22...

and thats it.

**Comment by RuneMykle** [comment]
Illustrating the issue:

http://exalted-gaming.com/necrogui/20160811_232421.mp4

**Comment by RuneMykle** [comment]
Visualizing the problem:

http://exalted-gaming.com/necrogui/necrobotgui.mp4

(Never mind the norwegian..)

**Comment by vandernorth** [comment]
Bøllock! looks like i forgot a few files in the release... let me fix this..

**Comment by vandernorth** [comment]
Can you please try and download the latest zip and see if it works? https://github.com/vandernorth/NecroBot.GUI/releases/tag/v0.3.2

**Comment by RuneMykle** [comment]
Testing it now

**Comment by RuneMykle** [comment]
Works! :+1:  :)
