### ISSUE TITLE
Noxx/dev Necro v0.9.3

### ISSUE THREAD

**Issue by LiraGamer** [vandernorth/NecroBot.GUI#110]
Noxx/dev update Necro v0.9.2
you can find it here: https://github.com/NoxxDev/NecroBot/releases/tag/v0.9.3

**Comment by parkpaya** [comment]
yesss pls update to v0.9.2 because it added very useful feature (Walk with GoogleMap Route)

**Comment by tmathura** [comment]
NoxxDev/NecroBot v0.9.3 was released. This has some nice anti ban stuff. Please can you use this.

https://github.com/NoxxDev/NecroBot/releases/tag/v0.9.3

**Comment by LiraGamer** [comment]
@tmathura Thank man
