### ISSUE TITLE
Map not display correctly & hang.

### ISSUE THREAD

**Issue by hefenglim** [vandernorth/NecroBot.GUI#112]
### Actual Behavior
start up program, map not display correctly with bot path location.
mouse click, zoom, drag move map, not respond, map windows hang.

Screenshot: 
![2016-08-19_132354](https://cloud.githubusercontent.com/assets/21117851/17799824/7fc12c2a-6610-11e6-977e-8ebf2d20cb1a.png)

### Other Information
Version: 0.5.0
Windows Version: Windows 7 Pro Build:7601
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): None

**Comment by golgolak** [comment]
sometimes it happens, just reload. also try zooming out.

**Comment by vandernorth** [comment]
There a reload button in the latest version. Can you check if that works for you?

**Comment by hefenglim** [comment]
Reload buttom work to get back map & mario. but when i zoom in more map become hang up, need to reload again. so currently zoom in will hang, and reload with far away look but no path line & pokestop.

Screenshot below reload finished, map can drag and move, cant see path line & pokestop.
![2016-08-22_205829](https://cloud.githubusercontent.com/assets/21117851/17855304/a2fdbfa4-68aa-11e6-9129-3e1953ccc102.png)

Zoom in one step. map hang, cant move. no mario.
![2016-08-22_210007](https://cloud.githubusercontent.com/assets/21117851/17855342/dc37e57e-68aa-11e6-8e0f-a1805e156330.png)
