### ISSUE TITLE
GUI Crashes

### ISSUE THREAD

**Issue by tmathura** [vandernorth/NecroBot.GUI#115]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Issue or feature request?
... Issue

### Expected Behavior
... GUI should not crash

### Actual Behavior
... GUI crashes. See error in image. and I have included the windows eventlog for this
[error.txt](https://github.com/vandernorth/NecroBot.GUI/files/426485/error.txt)
![1c2e173a-65ee-11e6-860a-5bfa6768c8ca](https://cloud.githubusercontent.com/assets/20637791/17811288/36f04046-6622-11e6-9224-f83a9e16475c.jpg)

### Steps to Reproduce
... Keep running for over a hour

### Other Information
Version: 0.50
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by jimmyxXx** [comment]
In my case it just shuts down without anything relevant in the log. Just now it shut down:
[09:25:37] Adding 145 to list
[09:25:37] Pokemons to evolve = 54
[09:25:38] Magikarp            	- CP: 10  IV: 63.75%   [Best CP: 107  IV: 89.91%] (Candies: 486)
[09:25:44] No listener for event KillSwitchEvent

And an hour before it shut down:
[08:32:07] Adding 142 to list
[08:32:08] Pokemons to evolve = 53
[08:32:08] Psyduck             	- CP: 43  IV: 46.72%   [Best CP: 616  IV: 87.26%] (Candies: 252)

In both cases it was "close" to half past the hour.

**Comment by vandernorth** [comment]
Thanks, the error.txt  is very helpfull. Will fix.

**Comment by tmathura** [comment]
no problem :+1:

**Comment by tmathura** [comment]
Thanks! :-)
