### ISSUE TITLE
Map icons missing (except for player icon and path)

### ISSUE THREAD

**Issue by raymonders** [vandernorth/NecroBot.GUI#118]
Topic says it all. But here's a picture anyway.
![boop](https://cloud.githubusercontent.com/assets/21112692/17815516/eca19a54-6634-11e6-9a56-913067b4bda3.JPG)

**Comment by czokalapik** [comment]
actually i have same problem, but pokestops appear after a while

**Comment by vandernorth** [comment]
I'm not really sure what happens here. What I see on my side:
- Map opens on the locations I've set in my config.json (Somewhere in Quebec)
- Map jumps to New York after 5 seconds and keeps walking there...

Is your issue similar to what I see?

**Comment by vandernorth** [comment]
Nevermind, found that...

**Comment by vandernorth** [comment]
Can you test with the latest version to see if this is resolved?

**Comment by czokalapik** [comment]
looks like it works properly

**Comment by czokalapik** [comment]
nope, still doesnt, on one launch there were pokestops, on another one only player and path

**Comment by raymonders** [comment]
Still getting it on the 5.1.
Agree with @czokalapik  it's not a consistent error

![again](https://cloud.githubusercontent.com/assets/21112692/17834632/45b8ebf4-674a-11e6-834c-9b8f96a8e478.JPG)

**Comment by czokalapik** [comment]
i THINK that bug is fixed in v0.5.2
or at least didn't happened to me since i updated to that version.
