### ISSUE TITLE
Automatically Closes

### ISSUE THREAD

**Issue by BonJaZu** [vandernorth/NecroBot.GUI#12]
When I open it it will Automatically close.

Initializing NecroBot logger at time 8/11/2016 6:55:32 PM...
Initializing NecroBot logger at time 8/11/2016 6:55:43 PM...
Initializing NecroBot logger at time 8/11/2016 6:57:54 PM...

Using PTC account.

**Comment by BonJaZu** [comment]
OK, so if you have this problem then change the Google name and pass to null (remove quotations)
and make sure to add quotations to your username and password on the PTC auth. 

Seems to be working fine now.

**Comment by vandernorth** [comment]
Thanks! I'll add a more default auth.json next time.
