### ISSUE TITLE
[bug] pokemon list not refreshing

### ISSUE THREAD

**Issue by czokalapik** [vandernorth/NecroBot.GUI#120]
### Issue or feature request?
issue

### Expected Behavior
after transfering, refreshing, or catching pokemon, list should be refreshed

### Actual Behavior
no changes to the list after transferring few mons and refreshing, list is not refreshing automatically also

### Steps to Reproduce
transfer few pokemons and try to refresh list

### Other Information
Version: v0.5.1
Windows Version: 8, x64
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):
managing pokemons

**Comment by vandernorth** [comment]
See #122
