### ISSUE TITLE
[request] force move to location

### ISSUE THREAD

**Issue by czokalapik** [vandernorth/NecroBot.GUI#121]
I'd like to see a feature to double click on map to "force move to location", after current action is completed, player will walk with it's normal walking speed to that location, catching pokemons and looting pokestops as usual.

MobBot have this feature, it's really helpful with catching rare pokemons, like when you farm in San Francisco and see dratini nearby on fastpokemap or skiplagged without teleporting.

**Comment by vandernorth** [comment]
Would be nice, not sure if I have the time though ;-)

**Comment by vandernorth** [comment]
Little bit related to #69
