### ISSUE TITLE
Pokemon list does not refresh

### ISSUE THREAD

**Issue by tmathura** [vandernorth/NecroBot.GUI#122]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Issue or feature request?
...Issue

### Expected Behavior
...The pokemon list to refresh when I press the refresh button

### Actual Behavior
...When I press the refresh button it does not refresh

### Steps to Reproduce
...Press the refresh button

### Other Information
Version: v0.5.1
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by raymonders** [comment]
Can confirm this issue. Manually transfered some stage 2 pokemon, transfer succesful. However when I presh refresh, the list does not update (the transfered pokemon are still there). Trying to transfer the same pokemon again results in (Transfer result: failed) Same issue when list updates automatically after capturing new pokemon.

**Comment by vandernorth** [comment]
Ah, this makes sense. Transfered pokemon are not deleted from the last. 

And apparently a pokemon gets a new UID when it evolves causing #127
