### ISSUE TITLE
[BUG] Snipe Conflict

### ISSUE THREAD

**Issue by LiraGamer** [vandernorth/NecroBot.GUI#124]
When the ("UseSnipeLocationServer": false = true) the bot lock to start is just exhibir the message ((info) there is in workspace.xml in your root directory to load.)

this is a NecroBot.GUI party in error because necroBOT everything works normally

**Comment by iamspa** [comment]
nothing wrong with that.
workspace.xml for necrobot GUI that you are edit the GUI, like font size of CLI and etc...

**Comment by vandernorth** [comment]
Error messages are unrelated indeed.  Nothing I can do here.

**Comment by PenjagaHati** [comment]
@vandernorth 
I also experienced like that , but just change false to true , no other change

**Comment by distantface** [comment]
I have the same problem,too.
I only change  "UseSnipeLocationServer" from false to true and it can't start.

**Comment by vandernorth** [comment]
Fixed in v0.5.2

**Comment by PenjagaHati** [comment]
ok,done (Y) thank
