### ISSUE TITLE
About new KillSwitch

### ISSUE THREAD

**Issue by raymonders** [vandernorth/NecroBot.GUI#125]
Hello!
I am confused as to how the Catch killswitch works in the new update. Is it still xx occurences per hour? Or is it now xx occurences per runtime?
Also, about the pokestop killswitch, is it also by hour? or per runtime?
Thanks!

P.S. I thought about asking this at the noxx hub, but people here are friendlier and more helpful. :+1:

**Comment by LiraGamer** [comment]
I also have the same doubts :D

**Comment by LiraGamer** [comment]
after performing some tests found that it's an hour and not by running a shame because I think it would be much more effective and utilizaveu executions to time inves!

**Comment by vandernorth** [comment]
This comes straight from the normal Necrobot.
