### ISSUE TITLE
Evolve Bug

### ISSUE THREAD

**Issue by Henaputi** [vandernorth/NecroBot.GUI#127]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr

### Issue or feature request?
Issue

### Expected Behavior
Pokemon that evolved should be replaced by the evolved pokemon in the list.

### Actual Behavior
The list has not been updated and the old pokemon is still in the list with its evolved form.

See attchment: [http://imageshack.com/a/img922/6854/2FdxxV.png](url)

![bug](https://cloud.githubusercontent.com/assets/21008091/17834720/96551d32-677f-11e6-902e-43bb87191ff8.PNG)

### Other Information
Version: 5.1
Windows Version: Windows 7
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): Evolve

**Comment by vandernorth** [comment]
But if you manually refresh everything is OK?

**Comment by vandernorth** [comment]
Will be solved by #122
