### ISSUE TITLE
Unicode Fancy Letters

### ISSUE THREAD

**Issue by Xerye** [vandernorth/NecroBot.GUI#128]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
Done.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
Done.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr
No its not ^_^

### Issue or feature request?

Issue.

### Expected Behavior

Runs smooth as it allways did, I love your GUI version :D

### Actual Behavior

As I use some fancy letters in unicode for naming my pokemon, the bot gives neverending debugmessages so I cannot click anything in the bot, cant change settings and such, because the debugmessage is allways in prioritywindow and blocks the actual bot-window.
Screenshot of the letters used:
http://imgur.com/a/srNKu
Same screenshot in attatchment! :)

Copy of the error-message:

"Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.FormatException: Die Eingabezeichenfolge hat das falsche Format.
   bei System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   bei System.Number.ParseUInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   bei ListViewColumnSorter.StringNum..ctor(String value)
   bei ListViewColumnSorter.Compare(Object x, Object y)
   bei System.Windows.Forms.ListView.CompareFunc(IntPtr lparam1, IntPtr lparam2, IntPtr lparamSort)
   bei System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   bei System.Windows.Forms.Control.DefWndProc(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ListView.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.6.1590.0 built by: NETFXREL2.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll.
----------------------------------------
NecroBot.GUI
    Assembly-Version: 0.4.2.1.
    Win32-Version: 0.4.2.1.
    CodeBase: file:///C:/Users/*******/Desktop/Main/PROGRAMME/BlueStacks/VANDERNORTH/NecroBot.GUI.exe."

### Steps to Reproduce

Copy some of these letters into the name of a pokemon ingame and start the bot, it directly gives the debugmessages as it cant handle those fancy letters:

๖ۣۜLtєรt tєאt (Ltest text)

### Other Information
Version: GUI 0.4.2, Necro 0.8.6
Windows Version: Windows 10, latest updates.
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup
![final_bstsnapshot_12292](https://cloud.githubusercontent.com/assets/21149771/17834802/3496c876-6751-11e6-95b8-2a0f7667715e.jpg)
, other):
Everything xD :D

**Comment by Xerye** [comment]
It would be much appreciated if you can show me a way to make this debugmessage-popup disappear, and to keep my fancy names :D 
Thanks in advice, and *bows* to your great work! :D

**Comment by Xerye** [comment]
Ps: Here I attatched the Popup-Window :) 
![error](https://cloud.githubusercontent.com/assets/21149771/17834816/462d7476-6752-11e6-8d27-683413225054.jpg)

**Comment by vandernorth** [comment]
Haha nice... this is in the sorting of the grids. Should be easy to fix ;-)

**Comment by Xerye** [comment]
Nice thank you :D No stress no stress and allready looking forward to it :D cheers m8
