### ISSUE TITLE
How can i fix this errors?

### ISSUE THREAD

**Issue by antibiotic1** [vandernorth/NecroBot.GUI#129]
I get errors when trying to compile source
1.The type or namespace name 'Model' does not exist in the namespace 'PoGo.NecroBot.Logic' (are you missing an assembly reference?)	PoGo.NecroBot.GUI	C:\Users\User\Documents\GitHub\NecroBot.GUI\GUI\PokeGUI.cs	13	Active

2.The type or namespace name 'GoogleWalkConfig' could not be found (are you missing a using directive or an assembly reference?)	PoGo.NecroBot.GUI	C:\Users\User\Documents\GitHub\NecroBot.GUI\GUI\PokeGUI.cs	380	Active

3.The command "if not exist "C:\Users\User\Documents\GitHub\NecroBot.GUI\NecroBot\PoGo.NecroBot.CLI\bin\x86\Debug\Resources" mkdir "C:\Users\User\Documents\GitHub\NecroBot.GUI\NecroBot\PoGo.NecroBot.CLI\bin\x86\Debug\Resources"
move /Y "C:\Users\User\Documents\GitHub\NecroBot.GUI\NecroBot\PoGo.NecroBot.CLI\bin\x86\Debug\*.dll" "C:\Users\User\Documents\GitHub\NecroBot.GUI\NecroBot\PoGo.NecroBot.CLI\bin\x86\Debug\Resources\"" exited with code 1.	PoGo.NecroBot.CLI			

4.'Navigation' does not contain a definition for 'WalkStrategy' and no extension method 'WalkStrategy' accepting a first argument of type 'Navigation' could be found (are you missing a using directive or an assembly reference?)	PoGo.NecroBot.GUI	C:\Users\User\Documents\GitHub\NecroBot.GUI\GUI\PokeGUI.cs	417	Active

5.'GlobalSettings' does not contain a definition for 'GoogleWalkConfig' and no extension method 'GoogleWalkConfig' accepting a first argument of type 'GlobalSettings' could be found (are you missing a using directive or an assembly reference?)	PoGo.NecroBot.GUI	C:\Users\User\Documents\GitHub\NecroBot.GUI\GUI\PokeGUI.cs	378	Active

Can someone, please tell me where i am doing my mistakes. I am very new to this. 
What i do is first open solution in NecroBot folder - NecroBot for Pokemon Go.sln in order to download the packages.  Then i open the main solution PoGo.NecroBot.GUI.sln and here also just a click on reload or how it was to downlaod the packages again. 
At my first step i dont get any error, but when opening the secound solution it gives me those 5 errors

**Comment by vandernorth** [comment]
You sure you've pulled the latest necrobot submodules? Seems like you still have an older version.

**Comment by antibiotic1** [comment]
doesnt your bot download automatically the latest version from necrobot?

**Comment by vandernorth** [comment]
Yeah it should, be they are git submodules.
So if you had my code for 0.4.1 checked out, then did a normal git pull to update to 0.5.1 then the submodules were not updated.

You need to recurse  the submodule as well like so:
git pull --recurse-submodules
