### ISSUE TITLE
[16:44:13] No usable PokeStops found in your area. Is your maximum distance too small?

### ISSUE THREAD

**Issue by Prilann** [vandernorth/NecroBot.GUI#132]
Hey, I have this error: [16:44:13] No usable PokeStops found in your area. Is your maximum distance too small?

I stopped it for 2 hours, restarted my pc and downloaded it again.
The first 24 hours it had works perfect.
I tried it on 2 accounts.

Version: 0.5.1
Windows Version: 10

**Comment by vandernorth** [comment]
Sounds like a ban to me.
