### ISSUE TITLE
No listener for event NewPathToDestinyEvent

### ISSUE THREAD

**Issue by Stiltman** [vandernorth/NecroBot.GUI#134]
So im not sure if this is an error or what it would be but thought id post it up here.

my "log" keeps showing every now and then, specially when heading towards a pokestop that is a bit further away from "center".

**(None) No listener for event NewPathToDestinyEvent.**

and when that happens the bot just skips the stop it was heading to and turns back to some of the other ones, making it waste lot of time since it sometimes were almost at the pokestop it was heading towards.
### Other Information

Version: 0.9.3
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by blaink** [comment]
same to me

**Comment by vandernorth** [comment]
The error is because we are not listening to that event... I'll listen to it in the next release, but the logic beneath it is Necrobot.
