### ISSUE TITLE
POGOProtos.dll Reference not found in PoGo.Necrobot.GUI

### ISSUE THREAD

**Issue by antibiotic1** [vandernorth/NecroBot.GUI#136]
I get this error when trying to compile the source code. What is the location you refer this reference to? I am so tired , and i want to make it work from source , but still the last error happens to me.
I think the problem is with POGOProtos.dll  or with Pokemon.Go.Rocket.API.dll.
Any chance someone helps me trought teamviewer to finaly make it working?
Thanks friends

**Comment by antibiotic1** [comment]
I saw your post now
"Found it, its the config, KillSwitchSettings is new and null by default. just put this in your config:
`KillSwitchSettings:{}"
Friend any way for you to import it? coz i thing this is a must now :)

**Comment by vandernorth** [comment]
Delete the reference and reference the project instead of the dll
