### ISSUE TITLE
Sniping with PogoLocationFeeder does not work

### ISSUE THREAD

**Issue by Xerye** [vandernorth/NecroBot.GUI#137]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check. Done.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead. Done.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/VXKxNFr
### Issue or feature request?

Issue.
### Expected Behavior

Starts sniping at pokestops by using the PogoLocationFeeder v0.1.8
https://github.com/5andr0/PogoLocationFeeder/releases
### Actual Behavior

It does not start sniping, nor gives any message about it, the character simply moves onto the next pokestop without a snipe :)
### Steps to Reproduce

Non actually I guess, but here are my snipingconfigs:
  "SnipingSettings": {
   "UseSnipeLocationServer": true,
   "SnipeLocationServer": "localhost",
   "SnipeLocationServerPort": 16969,
   "GetSniperInfoFromPokezz": false,
   "GetOnlyVerifiedSniperInfoFromPokezz": false,
   "GetSniperInfoFromPokeSnipers": false,
   "GetSniperInfoFromPokeWatchers": false,
   "GetSniperInfoFromSkiplagged": false,
   "MinPokeballsToSnipe": 20,
   "MinPokeballsWhileSnipe": 0,
   "MinDelayBetweenSnipes": 3000,
   "SnipingScanOffset": 0.003,
   "SnipeAtPokestops": true,
   "SnipeIgnoreUnknownIv": false,
   "UseTransferIvForSnipe": false,
   "SnipePokemonNotInPokedex": false
  },
### Other Information

Version: NecrobotGUI v0.5.2
Windows Version: Windows 10, latest updates
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):
Catch+Snipe

---

Hiho, me again :)
Big thanks for the previous fix of the fancy latters :D 
Looking pretty cool (screenshot attatched ^_^)
So, for this issue, I updated to the latest v0.5.2 NecrobotGUI and converted my former config into the new one. I setup sniping as it worked in the previous version, but now it doesnt start sniping at pokestops :D 
I put my snipeconfig aboth, incase its a settingissue (wich I guess its not) but you never know maybe im blind :D 
Anyways, I think the latest v0.5.2 NecrobotGUI somehow has an issue with the localhost sniping using the PogoLocationFeeder :)
Would be cool if you've time to take a quick look at, Im sure its only a little easy thing to fix :D 

Cheers and thanks!
![fancynames](https://cloud.githubusercontent.com/assets/21149771/17839937/95104b94-67f8-11e6-866b-0c0f48743ca6.jpg)

**Comment by Xerye** [comment]
Additional info:
The PogoLocationFeeder has his own filter and config .json's - they are all correct, so issues from "outside" can't be.

**Comment by Xerye** [comment]
And AGAIN additional info (sorry for the extracomments xD):
When I run Pogolocationfeeder, afterwards NecroGUI and close the Pogolocationfeeder then, there is no "Lost connection to localserver" in the NecroGUI console anymore.
Wich allways has been in the previous releases, so most likely the latest NecroGUI does not connect to the Localhost or needs a specified adress like 127.0.0.1 or something like that :D 
Hope thats helpful! :)

**Comment by LiraGamer** [comment]
same problem here!

**Comment by vandernorth** [comment]
But does this work with the native necrobot CLI?

**Comment by LiraGamer** [comment]
everything works with standard necroBot 0.9.4
