### ISSUE TITLE
Dragonite not showing in the "missing pokemon" list.

### ISSUE THREAD

**Issue by riccardonuzz** [vandernorth/NecroBot.GUI#138]
### Issue or feature request?
Dragonite not showing in the "missing pokemon" list.

### Expected Behavior
Dragonite should be displayed.

### Actual Behavior
Dragonite is missing in the list of "missing pokemon".

### Other Information
Version: Latest
Windows Version: Windows 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): UI

**Comment by tiagorosendo** [comment]
Fixed in #146

**Comment by vandernorth** [comment]
true
