### ISSUE TITLE
NecroBot Updates

### ISSUE THREAD

**Issue by Ghauk** [vandernorth/NecroBot.GUI#14]
How do we update the GUI when Necrobot updates.

**Comment by vandernorth** [comment]
Yeah that's sort of a 'problem' with how this GUI works as it integrated almost everything the bot can do. Auto update is going to be hard at this time. I'll release an updated version probably tomorrow.

**Comment by vandernorth** [comment]
See https://github.com/vandernorth/NecroBot.GUI/releases/tag/v0.3.3
