### ISSUE TITLE
load default location with inaccurate offset shift?

### ISSUE THREAD

**Issue by hefenglim** [vandernorth/NecroBot.GUI#140]
### Issue or feature request?
since every time start bot, with Fixed location Ex: 24.700752, 120.857324 from config.json file.
it is not make sense with real every time start up App with same location.
how about to auto shift little random offset load from config.json?
thanks.

### Other Information
Version: 0.5.1
Windows Version: Windows 7
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): None

**Comment by Xerye** [comment]
Good suggestion, would help hiding a bot.

**Comment by vandernorth** [comment]
isnt that what the offset location is for in the config (not sure)? 
I believe the new release of necrobot adds 'continue where previous session stopped'

**Comment by hefenglim** [comment]
is from config.

**Comment by vandernorth** [comment]
I think this is resolved by #153
