### ISSUE TITLE
Egg selection/priority

### ISSUE THREAD

**Issue by raymonders** [vandernorth/NecroBot.GUI#141]
### Issue or feature request?

feature request
### Expected Behavior

Implement an option to select which egg to incubate next, for example by right clicking the egg and pressing a button?
Or to select only 2km/5km/10km egg to incubate during a botting session

**Comment by vandernorth** [comment]
The last one is an option in necrobot I believe.

**Comment by raymonders** [comment]
The necrobot option only allows for the minimum type of egg to hatch. For example setting it to 2 means 2,5 and 10 eggs can be selected. Setting it to 5 means 5 and 10. I was wondering if there was a way to make it incubate ONLY one kind of egg?
