### ISSUE TITLE
 Bot doesn't open

### ISSUE THREAD

**Issue by HSMatheus** [vandernorth/NecroBot.GUI#143]
Already downloaded the net framework 4.6.2 , but  when I try to open the bot simply nothing happens. In Task Manager it appears for a few seconds but then suspended.

P.S: Windows 10 Pro 64x

![image](https://cloud.githubusercontent.com/assets/15190187/17870763/22029944-688f-11e6-96ff-9d5802fa2ee7.png)

**Comment by vandernorth** [comment]
delete all your config+auth+translations and try to start again.
