### ISSUE TITLE
Suggest random delay value.

### ISSUE THREAD

**Issue by hefenglim** [vandernorth/NecroBot.GUI#145]
### Issue or feature request?
Think to simulate more like human, like pokestop random need to stop or not?

current delay value:
"DelayBetweenPokemonCatch": 4000,
"DelayBetweenPlayerActions": 5000

Suggest add for:
DelayBetweenPokeStop : 3000
DelayPokeStopProbability : 0.5
DelayRandomMax: 5000

ex:
DelayRandomMax, random 0~5 secs value to add in all delay base for DelayBetweenPokemonCatch, DelayBetweenPlayerActions, DelayBetweenPokeStop.

I think this will help bot no static action loop for it.

### Other Information
Version: 0.5.2
Windows Version: Windows 7
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): None

**Comment by vandernorth** [comment]
You should suggest this at necrobot, not here.
