### ISSUE TITLE
- Necrobot-Private update v-0.9.8.6 - Noxx/dev NecroBot v0.9.7 to end

### ISSUE THREAD

**Issue by LiraGamer** [vandernorth/NecroBot.GUI#147]
### Issue or feature request?

att for necrobot v-0.9.8.6
link: https://github.com/NoxxDev/NecroBot/releases/tag/v0.9.7   *failed to end
Link: https://github.com/Necrobot-Private/NecroBot   *New
### Other Information

Version:
Windows Version: 8.1
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other):

**Comment by vandernorth** [comment]
I'm gonna wait until 0.9.7. I see there are a lot of commits since 0.9.6, I think 0.9.7 will be released soon.

**Comment by LiraGamer** [comment]
ok ! thank you very much
continue with good work

**Comment by LiraGamer** [comment]
update for 0.9.7

**Comment by parkpaya** [comment]
0.9.7 is more stable than previous version , please update :)

**Comment by LiraGamer** [comment]
https://github.com/Necrobot-Private/NecroBot
