### ISSUE TITLE
(issue) Lured pokestops don't update

### ISSUE THREAD

**Issue by raymonders** [vandernorth/NecroBot.GUI#148]
### Issue or feature request?

issue
### Expected Behavior

...
map display to show pokéstops with active lures
### Actual Behavior

...
doesnt show it
### Steps to Reproduce

... 
### Other Information

Version: bot 9.4, gui 5.2

**Comment by jimmyxXx** [comment]
And when the map does display an active lure, the lure is shown as active forever until restarting.
