### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by CreativiTimothy** [vandernorth/NecroBot.GUI#150]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Model.Settings.ClientSettings.PokemonGo.RocketAPI.ISettings.get_DefaultLatitude() in C:\webstorm\PoGo.NecroBot.GUI\PoGo.NecroBot.GUI\NecroBot\PoGo.NecroBot.Logic\Model\Settings\ClientSettings.cs:line 182
   at PokemonGo.RocketAPI.Client..ctor(ISettings settings, IApiFailureStrategy apiFailureStrategy) in C:\webstorm\PoGo.NecroBot.GUI\PoGo.NecroBot.GUI\NecroBot\FeroxRev\PokemonGo.RocketAPI\Client.cs:line 51
   at PoGo.NecroBot.Logic.State.Session.Reset(ISettings settings, ILogicSettings logicSettings) in C:\webstorm\PoGo.NecroBot.GUI\PoGo.NecroBot.GUI\NecroBot\PoGo.NecroBot.Logic\State\Session.cs:line 61
   at PoGo.NecroBot.Logic.State.Session..ctor(ISettings settings, ILogicSettings logicSettings) in C:\webstorm\PoGo.NecroBot.GUI\PoGo.NecroBot.GUI\NecroBot\PoGo.NecroBot.Logic\State\Session.cs:line 36
   at PoGo.NecroBot.GUI.PokeGUI.<botThreadWorker>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
NecroBot.GUI
    Assembly Version: 0.5.2.1
    Win32 Version: 0.5.2.1
    CodeBase: file:///C:/Users/Creat/Documents/Hacks/Pokemon%20Go/Necrobot%20GUI/NecroBot.GUI.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
ComponentFactory.Krypton.Toolkit
    Assembly Version: 4.4.1.0
    Win32 Version: 4.4.1.0
    CodeBase: file:///C:/Users/Creat/Documents/Hacks/Pokemon%20Go/Necrobot%20GUI/Resources/ComponentFactory.Krypton.Toolkit.DLL
----------------------------------------
PoGo.NecroBot.Logic
    Assembly Version: 0.9.4.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Creat/Documents/Hacks/Pokemon%20Go/Necrobot%20GUI/Resources/PoGo.NecroBot.Logic.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ComponentFactory.Krypton.Docking
    Assembly Version: 4.4.1.0
    Win32 Version: 4.4.1.0
    CodeBase: file:///C:/Users/Creat/Documents/Hacks/Pokemon%20Go/Necrobot%20GUI/Resources/ComponentFactory.Krypton.Docking.DLL
----------------------------------------
ComponentFactory.Krypton.Ribbon
    Assembly Version: 4.4.1.0
    Win32 Version: 4.4.1.0
    CodeBase: file:///C:/Users/Creat/Documents/Hacks/Pokemon%20Go/Necrobot%20GUI/Resources/ComponentFactory.Krypton.Ribbon.DLL
----------------------------------------
ComponentFactory.Krypton.Workspace
    Assembly Version: 4.4.1.0
    Win32 Version: 4.4.1.0
    CodeBase: file:///C:/Users/Creat/Documents/Hacks/Pokemon%20Go/Necrobot%20GUI/Resources/ComponentFactory.Krypton.Workspace.DLL
----------------------------------------
ComponentFactory.Krypton.Navigator
    Assembly Version: 4.4.1.0
    Win32 Version: 4.4.1.0
    CodeBase: file:///C:/Users/Creat/Documents/Hacks/Pokemon%20Go/Necrobot%20GUI/Resources/ComponentFactory.Krypton.Navigator.DLL
----------------------------------------
Pokemon.Go.Rocket.API
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Creat/Documents/Hacks/Pokemon%20Go/Necrobot%20GUI/Resources/Pokemon.Go.Rocket.API.DLL
----------------------------------------
POGOProtos
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Creat/Documents/Hacks/Pokemon%20Go/Necrobot%20GUI/Resources/POGOProtos.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.1.19813
    CodeBase: file:///C:/Users/Creat/Documents/Hacks/Pokemon%20Go/Necrobot%20GUI/Resources/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Google.Protobuf
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///C:/Users/Creat/Documents/Hacks/Pokemon%20Go/Necrobot%20GUI/Resources/Google.Protobuf.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by vandernorth** [comment]
Why didn't you use the issue template? no steps to reproduce or anything..
Looking at the stack trace this is something for necrobot.

**Comment by richie86** [comment]
manage to find out what the reason for this. Please make sure run the latest version once to generate the latest config structure. You will get this problem if you use old structure of config. New config structure is more organized.

**Comment by CreativiTimothy** [comment]
@vandernorth Sorry. Steps to reproduce is double-click the .exe to run it

**Comment by CreativiTimothy** [comment]
@richie86 I am running the lastest version and deleted old configs. Is it because I'm running Necrobot 9.6 and it's only compatible with 9.4?

**Comment by richie86** [comment]
@CreativiTimothy 
I used the latest release, run it to generate the new config. and migrate my old config to new config structure and it work.
https://github.com/vandernorth/NecroBot.GUI/releases/tag/v0.5.2

when you say u running necrobot 9.6? do you means you replace some of the DLL used ?
