### ISSUE TITLE
[Request]Illustration for inventory

### ISSUE THREAD

**Issue by LiraGamer** [vandernorth/NecroBot.GUI#152]
### Issue or feature request!
Illustration for inventory
I think it would be more pleasant to hear illustrations know it's something means more unnecessary is just a sujestão taking into account that is not something hard to do

### Actual Behavior
NoIllustration

### Other Information
Version: 0.5.2
For Version: 0.5.3

**Comment by efifi** [comment]
hardly of value?

**Comment by vandernorth** [comment]
Wont do.. You're free to submit a pull request, I'll accept it.
