### ISSUE TITLE
[REQUESTING] RUN NECROBOT V1.9.0 IN NET.FRAMEWORK 4.5.2

### ISSUE THREAD

**Issue by funkpunk8624** [vandernorth/NecroBot.GUI#156]
### Issue or feature request?

I want to request necrobot to run in net framework 4.5.2 for those low specification of system units.

**Comment by LiraGamer** [comment]
you should apply with necroBot distributors as NoxxDev
https://github.com/NoxxDev/NecroBot

**Comment by funkpunk8624** [comment]
How can i do it ? I dont know what did you mean too? Can you give me a instruction how it will work evwn at net.framework 4.5.2?
