### ISSUE TITLE
Map Issue

### ISSUE THREAD

**Issue by hptphuong** [vandernorth/NecroBot.GUI#157]
## Reload error

When I click on reload button, everything symbol about gym & pokestop on map are disapear.
## Zoom error:

I can't zoom in/out Map.
## Path gone:

Lack the function to view the path which my account visited

**Comment by LiraGamer** [comment]
which version you mean?

**Comment by hptphuong** [comment]
GUI V0.5.2 - Necrobot v0.9.4
One more, websocket function not working, I changed "UseWebsocket" to true. But its's not working.

**Comment by hptphuong** [comment]
Does anayone help idea to help me?
I'm using win 7 with netframework 4.6.2.
one more detail, when I choose max screen of map and zoom in (+), my map will be divided on two screen.
Please review on this picture.
https://www.dropbox.com/s/bh13q7wohcmfvj6/Capture.PNG?dl=0
