### ISSUE TITLE
Using old GUI with latest Bot?

### ISSUE THREAD

**Issue by raymonders** [vandernorth/NecroBot.GUI#158]
Was just wondering if it's possible to use the current GUI version with the latest necro fork? nothing else can compare to how easy it is to use Vandernorth's interface...

**Comment by HokoriXIII** [comment]
I`m trying to do it with new Necro, but there are a lot of problems/

**Comment by tmathura** [comment]
Is this project still being maintained? Because the last change was made something like two weeks ago

**Comment by LiraGamer** [comment]
Vandernorth said that waiting necro 0.9.7, but I think he left the project a little side ..

**Comment by raymonders** [comment]
i can get it to run with the new bot using a config structure for the last supported bot version necro9.4 (autoupdating from the GUI crashes the whole program), but then that means the bot doesnt use any of the new humanlike features :(
