### ISSUE TITLE
Request - Rename

### ISSUE THREAD

**Issue by RuneMykle** [vandernorth/NecroBot.GUI#16]
If possible, can you enable renaming through rightclick or doubleclick on Pokemon?

**Comment by vandernorth** [comment]
Good idea. Will do.

**Comment by hanncreator** [comment]
please update, im open always close

**Comment by vandernorth** [comment]
Added in v0.3.4 https://github.com/vandernorth/NecroBot.GUI/releases/tag/v0.3.4
