### ISSUE TITLE
Question about Necrobot takedown?

### ISSUE THREAD

**Issue by tws101** [vandernorth/NecroBot.GUI#160]
I noticed the github link 
https://github.com/NoxxDev/NecroBot/tree/v0.9.0

is shut down....  

Where did it move to?

**Comment by YouGamePlayHD** [comment]
I don't know. Why has it been taken down?!

**Comment by tws101** [comment]
The screen you get when you click it is the screen you get when Github closed your page.

So I imagine that Github was asked to close the page by niantic.

**Comment by raymonders** [comment]
this is some very disturbing news.

**Comment by tws101** [comment]
This popped up

https://github.com/Necrobot-Private/NecroBot

It is a continuation of the 9.0 fork.

**Comment by raymonders** [comment]
bless you @tws101

**Comment by smoothrunnings** [comment]
Where is the actual download link now? It's broken. :(
