### ISSUE TITLE
GUI not working

### ISSUE THREAD

**Issue by TheBlueHand** [vandernorth/NecroBot.GUI#164]
When i start up the Necrobot GUI it only shows a black map with spinning white wheels and I don't know what i can do to make it work. 
![necrobot](https://cloud.githubusercontent.com/assets/23506090/20357772/89e94174-ac29-11e6-9fa4-058fc55a8fa0.JPG)

**Comment by jjskuld** [comment]
First of all you are in the wrong GitHub repo. Go to https://github.com/Necrobot-Private/NecroBot

To answer your question, you need to download the console app and fire that up first. It will then send data to the gui.

**Comment by TheBlueHand** [comment]
I did that but it still doesn't work
