### ISSUE TITLE
With the recent announcement I guess it's over..

### ISSUE THREAD

**Issue by RuneMykle** [vandernorth/NecroBot.GUI#18]
https://github.com/NECROBOTIO/NecroBot

Announcement From Necrobots Discord:

@everyone
-Wcid - Today at 5:10 PM
@everyone  Due to legal action started and/or started against bot creators/devs we will have to say goodbye to this amazing community, this discord will remain open but all projects will be closed related to our beloved necrobot. We had fun, it was a nice time, but sadly we have to close up.. GG GF(edited)

I guess the bot and this gui will work until they change their api, but well.. 

Thanks for the effort you've put into this, Vandernorth! :)

**Comment by vandernorth** [comment]
Hmm probably... we'll see how long it keeps working... If somebody asks me to take this down I probably will... 

Thanks!
