### ISSUE TITLE
problem when compiling with vhost

### ISSUE THREAD

**Issue by samucarre** [vandernorth/NecroBot.GUI#19]
When compiling the program it gives me error when the program opens ' [ 8128 ] PoGo.NecroBot.GUI.vshost.exe ' ended with code 0 ( 0x0 ) . and when to open the reléase too.

**Comment by vandernorth** [comment]
Only that? No logs in the output of visual studio or anything?

**Comment by vandernorth** [comment]
Compiling should be better after next commit. Was compiling with static 'old' .dll files.
