### ISSUE TITLE
Program always close.

### ISSUE THREAD

**Issue by chillisbab** [vandernorth/NecroBot.GUI#22]
I dont know how the auth.json looks like formally. I try to login with google but if i start the program 2-3 sec and close. pls help me .

**Comment by hanncreator** [comment]
Change null in accout to
"Youremail"
"Yourpass"

**Comment by vandernorth** [comment]
Starting from 0.3.4 the botwil no longer close if you have invalid auth.json, Botwill stay open and you can see it in the logs.
