### ISSUE TITLE
my account softbanned

### ISSUE THREAD

**Issue by hanncreator** [vandernorth/NecroBot.GUI#23]
How to fix softbanned?
Your bot no auto unbanned bro?
Can you added unbanned in your bot?
Good job
And one more
Please fix click bot show error stopped

**Comment by vandernorth** [comment]
Can you explain "Please fix click bot show error stopped"? 
Where do you click? What error do you see?

**Comment by hanncreator** [comment]
![fb_img_14710931627370044](https://cloud.githubusercontent.com/assets/15106690/17643409/8a0a2de8-6193-11e6-8e35-d452e4d31c33.jpg)
How to fix?

**Comment by vandernorth** [comment]
Ah great! Can you show me what is under the "View problem details"?

**Comment by c2pillows** [comment]
i also got that crash just now. tried a few restarts that didnt help. it gave me these 3 files on the view problem details.


[WER85B3.tmp.appcompat.txt](https://github.com/vandernorth/NecroBot.GUI/files/416710/WER85B3.tmp.appcompat.txt)

[WER4D93.tmp.WERInternalMetadata.txt](https://github.com/vandernorth/NecroBot.GUI/files/416711/WER4D93.tmp.WERInternalMetadata.txt)


i couldnt send the other one but the file was WER85E3.tmp.mdmp

**Comment by wheychan** [comment]
I downloaded the Necrobot Gui but i can't find the exe file so that i can tun the bot. Please help me 😅

**Comment by hanncreator** [comment]
![13978206_135319193578079_1078543443_o png](https://cloud.githubusercontent.com/assets/15106690/17645065/713525ee-61c4-11e6-8b02-87df02d229e9.jpeg)
how to fix?
