### ISSUE TITLE
Is the trainer supposed to be just in the middle?

### ISSUE THREAD

**Issue by c2pillows** [vandernorth/NecroBot.GUI#24]
everything works, i can my pokemons on the pokemon tab, the pokemon i just caught on catches tab, the transfers are working too, i can see my latitude/longitude change also. its just the trainer looks likes he's only standing the red movement zone. it kinda bugs me since he was moving around at release v0.3.1. 

also the logging tab looks like it logs less going-ons. like before it logs which pokestop it is going and what items i got from the pokestop.

like i said the program works as a whole its just the less visual cues that is bugging me.

**Comment by vandernorth** [comment]
Yeah I just noticed the map is broken, already fixed that for the upcoming release. 
I'll also move back some more logging. (I was bugging me, because there was too much and I couldnt find what I was looking for, but now we have the colored logging which makes it all a bit better to read)

**Comment by c2pillows** [comment]
thanks for the clarification

**Comment by hanncreator** [comment]
![13978206_135319193578079_1078543443_o png](https://cloud.githubusercontent.com/assets/15106690/17644527/6ab205fe-61b3-11e6-926a-6b5f18007381.jpeg)
how to fix?
pokestop no unstable

**Comment by vandernorth** [comment]
This is in the latest release https://github.com/vandernorth/NecroBot.GUI/releases
