### ISSUE TITLE
NoxxDev forked from NECROBOTIO/NecroBot

### ISSUE THREAD

**Issue by sawako9** [vandernorth/NecroBot.GUI#27]
https://github.com/NoxxDev/NecroBot
Maybe, you can use this one for next releases.

**Comment by RuneMykle** [comment]
Better to look into YoBo (You're only banned once)
Some of the guys from the necro team continuing the show

**Comment by alonoe** [comment]
@RuneMykle repo link?

**Comment by RdKoyoe** [comment]
0.8.8 is released

**Comment by vandernorth** [comment]
Not sure how 'official' this one is? 
https://github.com/NECROBOTIO/NecroBot/tree/e4686900abe46d90284c62bc693fd37d067e0584

**Comment by LiraGamer** [comment]
some necro dev´s are updating again!
It is official yes

**Comment by RuneMykle** [comment]
http://prnt.sc/c63i76 
0.8.9

**Comment by RuneMykle** [comment]
0.8.9
https://github.com/NoxxDev/NecroBot/releases/

**Comment by LiraGamer** [comment]
att this man

**Comment by XoverheatX** [comment]
Hei van, can u give a feature like a proxy switcher 😂

**Comment by tmathura** [comment]
Not sure if this will help but saw in one of the issues for NoxxDev that the devs are not responding  according to one guy (https://github.com/NoxxDev/NecroBot/issues/125)

Suggested to use: https://github.com/plgonzalezrx8/MagicPoGoBot

I am not sure if this is valid or that fork is any better.

**Comment by vandernorth** [comment]
I've seen a commit by noxxDev less than an hour ago, so currently I'm trying to stick with that fork.

**Comment by RuneMykle** [comment]
Yeah, seems active enough
https://github.com/NoxxDev?tab=activity

**Comment by tmathura** [comment]
I see, that other must want people to use his bot :-1:

**Comment by vandernorth** [comment]
@tmathura  what do you mean?

**Comment by vandernorth** [comment]
Got my local branch working with v0.9.0 
Everything seems to work just fine, except you loose your config.json because it is restructured, nothing to do about that...

**Comment by tmathura** [comment]
@vandernorth, it seems like the developer of (https://github.com/plgonzalezrx8/MagicPoGoBot) wants to discredit the Noxx developers so that users can rather use his bot,
