### ISSUE TITLE
Elvolve crash

### ISSUE THREAD

**Issue by hanncreator** [vandernorth/NecroBot.GUI#29]
![13920885_1246179485455066_1772707457924710443_n](https://cloud.githubusercontent.com/assets/15106690/17645267/a4ca3786-61ca-11e6-93ba-d54a655c0f40.jpg)
whats this error ?

**Comment by vandernorth** [comment]
Can you copy paste what is under the details button?

**Comment by hanncreator** [comment]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.GUI.PokeGUI.<evolvePokemon>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
PoGo.NecroBot.GUI
    Assembly Version: 0.3.4.1
    Win32 Version: 0.3.4.1
    CodeBase: file:///D:/POKEMON/PoGo.NecroBot.GUI.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
ComponentFactory.Krypton.Toolkit
    Assembly Version: 4.4.1.0
    Win32 Version: 4.4.1.0
    CodeBase: file:///D:/POKEMON/ComponentFactory.Krypton.Toolkit.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ComponentFactory.Krypton.Docking
    Assembly Version: 4.4.1.0
    Win32 Version: 4.4.1.0
    CodeBase: file:///D:/POKEMON/ComponentFactory.Krypton.Docking.DLL
----------------------------------------
ComponentFactory.Krypton.Ribbon
    Assembly Version: 4.4.1.0
    Win32 Version: 4.4.1.0
    CodeBase: file:///D:/POKEMON/ComponentFactory.Krypton.Ribbon.DLL
----------------------------------------
ComponentFactory.Krypton.Workspace
    Assembly Version: 4.4.1.0
    Win32 Version: 4.4.1.0
    CodeBase: file:///D:/POKEMON/ComponentFactory.Krypton.Workspace.DLL
----------------------------------------
ComponentFactory.Krypton.Navigator
    Assembly Version: 4.4.1.0
    Win32 Version: 4.4.1.0
    CodeBase: file:///D:/POKEMON/ComponentFactory.Krypton.Navigator.DLL
----------------------------------------
PoGo.NecroBot.Logic
    Assembly Version: 0.8.6.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/POKEMON/PoGo.NecroBot.Logic.DLL
----------------------------------------
Pokemon.Go.Rocket.API
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/POKEMON/Pokemon.Go.Rocket.API.DLL
----------------------------------------
POGOProtos
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/POKEMON/POGOProtos.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.1.19813
    CodeBase: file:///D:/POKEMON/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Google.Protobuf
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///D:/POKEMON/Google.Protobuf.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
GPSOAuthSharp
    Assembly Version: 0.0.5.0
    Win32 Version: 0.0.5.0
    CodeBase: file:///D:/POKEMON/GPSOAuthSharp.DLL
----------------------------------------
System.Data.HashFunction.xxHash
    Assembly Version: 1.8.2.2
    Win32 Version: 1.8.2.2
    CodeBase: file:///D:/POKEMON/System.Data.HashFunction.xxHash.DLL
----------------------------------------
System.Data.HashFunction.Core
    Assembly Version: 1.8.2.2
    Win32 Version: 1.8.2.2
    CodeBase: file:///D:/POKEMON/System.Data.HashFunction.Core.DLL
----------------------------------------
System.Data.HashFunction.Interfaces
    Assembly Version: 1.0.0.2
    Win32 Version: 1.0.0.2
    CodeBase: file:///D:/POKEMON/System.Data.HashFunction.Interfaces.DLL
----------------------------------------
Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
    CodeBase: file:///C:/Windows/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------
GeoCoordinatePortable
    Assembly Version: 0.1.0.0
    Win32 Version: 0.11.0
    CodeBase: file:///D:/POKEMON/GeoCoordinatePortable.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
S2Geometry
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/POKEMON/S2Geometry.DLL
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Extensions.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by vandernorth** [comment]
Ah, I see... You are trying to evolve a pokemon that cannot be evolved (not evolvable or not enough candy)

**Comment by hanncreator** [comment]
oh yes, sorry van. 
thanks for solved :D
