### ISSUE TITLE
Hei devs, this error my pc or my account ? -_-

### ISSUE THREAD

**Issue by hanncreator** [vandernorth/NecroBot.GUI#30]
i have problem always use bot :(
![14012248_120300000064366975_1639394468_n png](https://cloud.githubusercontent.com/assets/15106690/17645406/a0fdec06-61cf-11e6-8a02-81a760229f71.jpeg)

**Comment by vandernorth** [comment]
Normally means softban. Close the bot try again in 1 hour.
