### ISSUE TITLE
[Question] do we need necrobot to run this

### ISSUE THREAD

**Issue by daproject85** [vandernorth/NecroBot.GUI#31]
Hi , I am looking at the directory structure, its liek necrobot..

so we need necrobot? or is it built in?

**Comment by vandernorth** [comment]
Its build in.

**Comment by daproject85** [comment]
which version? 

Regards,

Rocky Rashidi

**Comment by vandernorth** [comment]
v0.8.5

**Comment by daproject85** [comment]
.8.8 came out, will it be updated ?


Regards,

Rocky Rashidi

**Comment by vandernorth** [comment]
Well, its not an official necrobot release since they are offline. I'll have to look into it, updating request is in #27

**Comment by daproject85** [comment]
cuz the new one has some things to help with ban and shit :) 

Regards,

Rocky Rashidi
