### ISSUE TITLE
[Bug] Stop working when call  /status from telegram

### ISSUE THREAD

**Issue by ttpro1995** [vandernorth/NecroBot.GUI#34]
NecroBot.GUI stop working when I try to call /status from telegram.
Other commands such as  /top   /all  /profile  /loc  /items   /pokedex still functional.

**Comment by vandernorth** [comment]
Does it hang, or does give an error message?

**Comment by ttpro1995** [comment]
It stop working. Windows show the popup " ... has stop working".

**Comment by ckmkaya** [comment]
i have this issue too.

**Comment by vandernorth** [comment]
I've seen fixes in newer Necrobot releases, this will probably be fixed when #27 is resolved.

**Comment by vandernorth** [comment]
Should be fixed in v0.5.0, please test when it is out.
