### ISSUE TITLE
[Contribution needed] Implemented alternative map (e.g. Bing)

### ISSUE THREAD

**Issue by wuonly** [vandernorth/NecroBot.GUI#36]
thanks for the GFW, Google maps can not use in China
maybe  u can change to use other maps

**Comment by vandernorth** [comment]
Suggestions?

**Comment by wuonly** [comment]
Use Bing Map instead?

**Comment by HZH1907** [comment]
@wuonly 
自己挂个vpn不好?hosts也行啊....
https://github.com/racaljk/hosts
像这样改个hosts 也不用开发者硬是改了接口

**Comment by vandernorth** [comment]
Ok, I'm not gonna have time for this... If there is any other dev who wants to contribute, please feel free to do so...
