### ISSUE TITLE
It crashes when loggin

### ISSUE THREAD

**Issue by JoNMii** [vandernorth/NecroBot.GUI#38]
It says loggeds as Xusername, and then it crash. No log output. And no crash output on console.

**Comment by vandernorth** [comment]
I need more info...
Whats in the log file in the ./Logs directory?
Any messages what so ever?

**Comment by RuneMykle** [comment]
Try to turn off sniping perhaps?

**Comment by JoNMii** [comment]
In the log directory only says Initializing NecroBot logger at time 14/08/2016 ....

It crashes when says playing as .. check alt/lat then crash

**Comment by JoNMii** [comment]
Snipe is off

**Comment by JoNMii** [comment]
I think it was because im banned xDD
