### ISSUE TITLE
sniping?

### ISSUE THREAD

**Issue by b0mb4rd** [vandernorth/NecroBot.GUI#4]
Sniping doesnt seem to work.
Great work anyway
Thx

**Comment by vandernorth** [comment]
I've never sniped, can you tell me how you tested? I'll look into it.

**Comment by b0mb4rd** [comment]
several ways but certainly the easiest is to use the 2 lines in bot's config 
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
and run run PogoLocationFeeder locally on same port before running the bot

**Comment by b0mb4rd** [comment]
I did but doesnt show btw

**Comment by RuneMykle** [comment]
This already works on my end mate. Sniping like a pro from Pogo.. :)
![2016-08-11_14h46_45](https://cloud.githubusercontent.com/assets/11351333/17588994/7a6508ee-5fd2-11e6-9fd5-9ff327e3f327.png)

**Comment by xratedownz** [comment]
@RuneMykle It is not pogo you are using. It is necrobot sniping. We would like to use pogo feeder with this gui.

**Comment by vandernorth** [comment]
External sniper code was missing, is added in the next release.

**Comment by vandernorth** [comment]
Fixed in https://github.com/vandernorth/NecroBot.GUI/releases/tag/v0.3.2
