### ISSUE TITLE
Is it possible to plot route where Bot are going on the map

### ISSUE THREAD

**Issue by parkpaya** [vandernorth/NecroBot.GUI#40]
Is it possible to plot route where Bot are going on the map? (Maybe GUI option?)

Thanks for your hard work.

**Comment by vandernorth** [comment]
Do you mean plot the route when using a GPX file? Or do you want the 'random' route to be visualized?

**Comment by midascodebreaker** [comment]
i think  he is saying is that if you can plot the path, upon loging in,
since there are pokestops loaded after logging in...
you can plot the path visually thru that

**Comment by parkpaya** [comment]
I mean both of it.

**Comment by RuneMykle** [comment]
Traced route with pokemons catched would be nice, not very useful, but nice :)

**Comment by vandernorth** [comment]
Simple plot of walked route has been added to v0.4.2

**Comment by tmathura** [comment]
Iit says it is in v0.4.2, I am just wondering how do I do this?

**Comment by vandernorth** [comment]
I assumed this issue was only to plot what HAS been walked, there is another issue for plotting something yourself.

**Comment by tmathura** [comment]
I am not sure if I understand you correctly, so it the plot stored somewhere? Is it what is in the logs?

Example: 

[16:00:03] Position changed. lat=-33,95757, lng=18,46034
[16:00:03] Looking for Pokemon...
[16:00:04] Looking for incense Pokemon...
[16:00:05] Position changed. lat=-33,95759, lng=18,46033

Is this what you mean plot what has been walked?

**Comment by vandernorth** [comment]
No, there should be a red line on the map where you have walked.

**Comment by tmathura** [comment]
okay, I understand the solution now :-) thanks!
