### ISSUE TITLE
Request - Managing inventory items

### ISSUE THREAD

**Issue by ghost** [vandernorth/NecroBot.GUI#41]
Hi vandernorth:

First of all huge thanks for all the effort you have put into this project. It's an amazing program super useful not only for botting but to manage pokemons. I think it would be a great addition to your program to be able to manage inventory items by right clicking on the items, so hence the request for:

1) Enable/start a lucky egg (that way we could do evolutions at 2X the XPs)
2) Delete other items (revive, potions, balls, etc...)

Of course enabling lucky eggs would be very useful and a great addition. Deleting other items is a nice to have but not as useful.

Again thanks a lot for your work!

**Comment by vandernorth** [comment]
WIll do!

**Comment by vandernorth** [comment]
Thanks!

Fixed in 0.4.1
