### ISSUE TITLE
Request - Favorite

### ISSUE THREAD

**Issue by larin003** [vandernorth/NecroBot.GUI#45]
Just like there was a way to rename Pokemons it would be nice to include in the right-click menu a way to make Pokemons "Favorite".

PS: When renaming Eevees and then elvolving from the program it does not evolve to the correct Pokemon like when using the actual game. Any reason for this?

Thanks a lot for you hard work!

**Comment by midascodebreaker** [comment]
bump

**Comment by vandernorth** [comment]
I think the actual game has stopped doing the thing with Eevee's name. I had tried it several times last week but it didnt work any more (in the actual game)

**Comment by vandernorth** [comment]
Fixed in v0.4.2
