### ISSUE TITLE
Reuest (autologin - autologoff)

### ISSUE THREAD

**Issue by mirdhan123** [vandernorth/NecroBot.GUI#46]
can you add auto login/logoff based on the number pokestop we have spinned?
ex: the bot will logoff after we have spin 200 pokestop

**Comment by vandernorth** [comment]
Do you want the bot to stop completely after 200 pokestops, restart directly or restart with delay?

**Comment by RogueMaster** [comment]
Can you make it restart immediately with a secondary account?

**Comment by vandernorth** [comment]
Sort of duplicate of #63 Lets continue there.
