### ISSUE TITLE
about transter pokemon

### ISSUE THREAD

**Issue by tiancris164** [vandernorth/NecroBot.GUI#49]
how to code,
i want to be transfer all pokemon with duplicate and has low CP
thanks

**Comment by RuneMykle** [comment]
This isn't gui related.

But:
  "KeepMinCp": 1250, <--- or whatever your min CP is
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 1,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,

**Comment by tiancris164** [comment]
i config it myself then the result all the pokemon are transfer. so sad

thanks for the reply.
