### ISSUE TITLE
moves not showing

### ISSUE THREAD

**Issue by b0mb4rd** [vandernorth/NecroBot.GUI#5]
Fast and charge attacks columns would be great ;)

**Comment by vandernorth** [comment]
I'll add the columns to the pokemon list. (I'm open for pull requests if you feel like editing it yourself ;-))

**Comment by b0mb4rd** [comment]
sorry i dont know how to do that

**Comment by vandernorth** [comment]
Fixed in the upcoming release v0.3.2

**Comment by vandernorth** [comment]
Fixed in https://github.com/vandernorth/NecroBot.GUI/releases/tag/v0.3.2
