### ISSUE TITLE
Request - Auto scroll 'Catches'

### ISSUE THREAD

**Issue by RuneMykle** [vandernorth/NecroBot.GUI#50]
When all is working well the only fun thing to do is to watch for catches, please make it auto-scroll.

**Comment by RuneMykle** [comment]
Found out there was no major need for this one, for me at least. 
- By sorting by the column I find of most interest the new ones will auto pop to the top if I catch them, leaving the ones with least interest at the bottom and out of sight which is good.

**Comment by vandernorth** [comment]
Should I make all grids sort on time and descending? 
Or ascending with autoscroll to end?

**Comment by RuneMykle** [comment]
Time and descending is probably the best.

(I should have had a small chat with you if possible, anyway to get in touch?)

**Comment by vandernorth** [comment]
Ok, that'll be the default starting from v0.4.2
