### ISSUE TITLE
Request - Max power up

### ISSUE THREAD

**Issue by RuneMykle** [vandernorth/NecroBot.GUI#52]
I got a 100 IV Snorlax and decided to Power it up. After repeating the power up 13-15 times my mind wandered off and I accidentally transferred it instead.. A waste of a perfect pokemon and tons of dust in other words, but completely my own fault.. :)

So, the request:
Can you implement a feature for "Max power up"? Which of course takes some time, just as batch transferring several pokes, but will power up your pokemon till it's either; max level, no more candy or no more dust.

This would make the process of powering up a good pokemon a lot less risky as one only does the power-up once. (Even though it will take some time)

**Comment by vandernorth** [comment]
Added in v0.4.2
