### ISSUE TITLE
Bug - Pokestops not refreshing on the map when walking past initial radius

### ISSUE THREAD

**Issue by ridalarry** [vandernorth/NecroBot.GUI#53]
Implement the pokestops and pokemons to appear in the map just like https://github.com/nicoschmitt/necrobotvisualizer

**Comment by vandernorth** [comment]
It should do that, but sometimes it doesnt.... mostly when you are (partly) banned...

**Comment by jimmyxXx** [comment]
I have never seen pokemon show on the map... has that ever worked? Or were you referring to pokestops (which show up initially, but sometime the next batch doesn't update). Also, it would be kind of cool to show the bot's path on the map. Not really useful per say, just looks cool :)

**Comment by vandernorth** [comment]
Nah, Pokemon did never show up, I did indead refer to the pokestops. 
Route plotting is added to the next version :-)

**Comment by vandernorth** [comment]
If someone can look at my pokestops-refresh implementation... It nevers seems to refresh properly (never did anyhow)
