### ISSUE TITLE
Which necro is in the newest version. 

### ISSUE THREAD

**Issue by daproject85** [vandernorth/NecroBot.GUI#54]

**Comment by thosuperman** [comment]
v0.8.6

**Comment by daproject85** [comment]
Plans to upgrade ?

**Comment by RuneMykle** [comment]
0.8.6 was the latest official version.

http://www.idigitaltimes.com/pokemon-go-necrobot-shuts-down-cheating-software-removed-developers-550219

(There has been some minor upgrades though since then, making the "latest" 0.8.8?)

I would go for YoBo for the future though.

**Comment by vandernorth** [comment]
See #27 for upgrading to newer version... not sure at this moment which 'official' one to use..
