### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by tharnnatee** [vandernorth/NecroBot.GUI#55]
google Username Password added but Not working.
<a href="http://www.mx7.com/view2/zipC9uabmcAZYJ9N" target="_blank"><img border="0" src="http://www.mx7.com/t/11a/RSwV7t.png" /></a>

**Comment by RuneMykle** [comment]
cant see your image, but add it with "'s

```
  "GoogleUsername": "yourgmailname@gmail.com",
  "GooglePassword": "yourpassword",
```

**Comment by richardSeti** [comment]
google is fine with " . but it can't log in using ptc

**Comment by tharnnatee** [comment]
Its work!! 
Thank you Guys
