### ISSUE TITLE
Incubator and Egg errors

### ISSUE THREAD

**Issue by Trolha69** [vandernorth/NecroBot.GUI#56]
Don't know if this is happening to other issues, but either way I'll leave it there. Can someone explain why it returns those errors? I think its only once per bot initialization.

http://imgur.com/a/SE5Jh
http://imgur.com/a/MkiU1

Thanks for an awesome bot!

**Comment by LiraGamer** [comment]
your config error !
  "UseEggIncubators": true,
  "UseEggIncubatorMinKm": 0, *or 1

**Comment by Trolha69** [comment]
But there aren't any 1Km eggs, why should I change it? Those values are the ones that came with the default config, I haven't changed them. And I never had this issue back with Necrobot.

**Comment by LiraGamer** [comment]
I was having the same problem as you and I did it is now he's brooding the eggs properly!

**Comment by Trolha69** [comment]
Ok, will try with your suggestion.

Meanwhile if @vandernorth could chime in and shine some light on this, I'd appreciate!

**Comment by LiraGamer** [comment]
he is working on at the moment 0.4.2

**Comment by vandernorth** [comment]
These errors have possibly been happening since forever, but they where not logged (not in the original bot nor in earlier releases of my bot). So these are relatively new to me, I've been logging them since v0.4.1. I'll dig in a little deeper if I have the time.

**Comment by Trolha69** [comment]
@vandernorth Thank you very much. But don't dwell too much on this, I merely reported because like I said earlier Necrobot never returned these 2 errors. Just focus on improving the bot and leave this for later! Thank you very much for such an amazing job, the bot looks beautiful!

**Comment by vandernorth** [comment]
Thanks! Yeah I'll leave this for the Necrobot core, it's not in 'my' part of the code.
