### ISSUE TITLE
When running through midnight lists stop updating

### ISSUE THREAD

**Issue by jimmyxXx** [vandernorth/NecroBot.GUI#58]

**Comment by jimmyxXx** [comment]
Logs are still being saved to files

**Comment by vandernorth** [comment]
Which lists? Is the on-screen logging being updated?

**Comment by jimmyxXx** [comment]
Yes - list of pokestops for sure, probably the other ones too (I checked early this morning, still half asleep)

**Comment by jimmyxXx** [comment]
Screenshot showing pokestops & catches not updating after midnight (but logging window is) (also showing that not all pokestops are shown on the map) (also showing that showing the path looks pretty cool :) )

![image](https://cloud.githubusercontent.com/assets/20912831/17696050/e71d829a-6379-11e6-9889-6b4130ea4358.png)

**Comment by abhay4sengars** [comment]
Facing the same problem here and also the map is messing up and showing 503 error

**Comment by jimmyxXx** [comment]
Actually this is looking like a more minor problem, but hopefully easy to fix: it just seems like the grids are sorted using time only, instead of date + time. When crossing midnight, the new events show up at the bottom of the list instead of the top. Please see screenshot below.

![image](https://cloud.githubusercontent.com/assets/20912831/17700629/9ff45374-6394-11e6-9260-4c0539365ec4.png)

**Comment by vandernorth** [comment]
@jimmyxXx yeah thats true... its time only xD I'll add dates as well.
