### ISSUE TITLE
Prevent new ban types

### ISSUE THREAD

**Issue by jimmyxXx** [vandernorth/NecroBot.GUI#59]
As described at https://www.reddit.com/r/pokemongodev/comments/4xkqmq/new_ban_types_and_their_causes/?st=irv7qkkw&sh=51f85965

Pokestop ban:
- Occurs when you search roughly 2k pokestops in a 23 hour timespan.
- No bypasses known.

Pokemon ban:
- Occurs when you catch 1k pokemon in a 23 hour timespan.
- Potential bypass by throwing missing pokeballs 15-30 times. (I haven't confirmed)

Stop before searching 2000 pokestops in 23 hours? I supposed it is not possible to get a "number of pokestops" searched in the last 23 hours from server? Because I often start & stop the bot, is there a way to know how many pokestops were looted across sessions (or even on other devices, like when I do manually on my phone)? Likewise for pokemon caught...

**Comment by vandernorth** [comment]
Hmmm could store it in a file... But I think I'll leave this one to the underlying Necrobot core. Hope one of the new dev's integrates this in one of their releases. Then I'll update via #27.
These seem like a big think they'll implement as soon as they can...
