### ISSUE TITLE
everytime i leave it overnight, the morning i get softban.

### ISSUE THREAD

**Issue by mcfinestlord** [vandernorth/NecroBot.GUI#61]
everytime i leave it overnight, the next morning i get softban that ban bypass won't fix.
I think its because i reached 2k pokestops or catched 1k pokemns? can u make somethjing to fix or bypass this ban?? thank you for reading

**Comment by abhay4sengars** [comment]
I second this, but I would love to have a terminate bot sort of thing before the threshold of Pokemon/day and Pokestops/day is reached and also if we can set the amount. Would love this feature.

**Comment by jimmyxXx** [comment]
As a temporary work-around, you can lower the walking speed when letting it run overnight. I set a walking speed of 20km / hr, and visited 1350 pokestops and caught 839 pokemon overnight.

**Comment by vandernorth** [comment]
Some good suggestions in #63  I'll close this one as a sort of pre-duplicate.
