### ISSUE TITLE
Necronbot 8.8 att for new 9.0

### ISSUE THREAD

**Issue by LiraGamer** [vandernorth/NecroBot.GUI#62]
your use Necro 9.0 ofical em new release.
http://www.mpgh.net/forum/showthread.php?t=1154457

**Comment by f3l1p1nh07** [comment]
http://i.imgur.com/2ghAYvo.png

Add this function please 

Killswitch - Going to be away from your computer? Set a killswitch value to have the bot close once a certain number of Pokemon are caught or Pokestops are looted.

**Comment by vandernorth** [comment]
Duplicate of #27
