### ISSUE TITLE
Feature Request - Add 1 Form to Edit Config

### ISSUE THREAD

**Issue by nighttiger1990** [vandernorth/NecroBot.GUI#66]
1. Can you make 1 Form to Edit Config.json?. Like below:
2. Power Up max, should be Max is (Trainer +1.5 Lvl. in game) (Bot can up Trainer + 2lvl)
3. Can you send me Full_SourceCode NecroBot v0.8.6 to : truongblt@gmail.com
Thanks for hard working!!
![capture](https://cloud.githubusercontent.com/assets/21042933/17686719/1118ebd8-6399-11e6-86d9-bb1ecbed6180.PNG)

**Comment by vandernorth** [comment]
1. Its on my list
2. Can you explain what you mean?
3. Its the zip in the root of the repo :-)

**Comment by nighttiger1990** [comment]
2. Ingame, Max lvl Pokemon = lvl Trainer + 1.5 (using Power Up)
But when using Bot. Lvl Pokemon reach : Lvl Trainer + 2. That's mean we will be detected using 3rd party tools.
3. I downloaded the Zip download but  don't see NecroBot v0.8.6 in zip file.

**Comment by RuneMykle** [comment]
[Necrobot_Release_0_8_6.zip](https://github.com/vandernorth/NecroBot.GUI/files/422155/Necrobot_Release_0_8_6.zip)

Hoping that vandernorth can include 0.9.0 soon though :)

**Comment by nighttiger1990** [comment]
@runemykle i need source code not realease, thanks

**Comment by nighttiger1990** [comment]
@vandernorth fix (2.) in next version and please give me a link to download Source Code v0.8.6 NecroBot Thanks verymuch!!
truongblt@gmail.com

**Comment by vandernorth** [comment]
I've just updated to 0.9.0 using submodules, so if you checkout the latest version of my repo, you'll have it all!

**Comment by nighttiger1990** [comment]
I really want v0.8.6 but thanks anyway...

**Comment by vandernorth** [comment]
If you really want them, look for the .7z file in one of the older commits.
