### ISSUE TITLE
update Necrobot to version 0.90

### ISSUE THREAD

**Issue by iamspa** [vandernorth/NecroBot.GUI#67]
sir...
can you update the necro bot to lastest version?
https://github.com/NoxxDev/NecroBot/releases/
because it fix lot than previous release....

**Comment by RuneMykle** [comment]
Runtime 2 hours on this one now with no problems at my end.

**Comment by vandernorth** [comment]
Duplicate of #27

**Comment by iamspa** [comment]
sry for duplicate, because just download and read Issue....
thank for such nice tools....
