### ISSUE TITLE
Source program missing

### ISSUE THREAD

**Issue by ChenQiuming** [vandernorth/NecroBot.GUI#68]
PoGo.NecroBot.Logic
POGOProtos
PoGo.NecroBot.CLI
PokemonGo.RocketAPI.csproj

Can you offer it to me? I need to make a Chinese version。
Thanks very much
my maill：xxtting@qq.com

**Comment by tmathura** [comment]
Were you able to get this? Because I am also looking for it.

**Comment by vandernorth** [comment]
Its the zip in de root directory of the repository :-)
