### ISSUE TITLE
[Suggestion] Custom Route

### ISSUE THREAD

**Issue by ptanhkhoa** [vandernorth/NecroBot.GUI#69]
The route on the map is nice, :D, but it  make me an idea that: 
Could you implemented custom route map, like we can draw on the map with these pokestop on and save it as gpx file. It easier for us to draw when we see all pokestop on the map.

**Comment by vandernorth** [comment]
I like the idea, but I think it will require a lot of time, I'll put it on my longer-term list ;-)
