### ISSUE TITLE
Request - Bulk operations with right-click

### ISSUE THREAD

**Issue by RuneMykle** [vandernorth/NecroBot.GUI#7]
I love the fact that I can transfer, evolve and power-up pokemons directly from within the GUI, but while sniping I often end up with a whole lot pokes that have a way too low IV for me to keep, resulting in  alot of single transferring which takes forever.

I would love it if I could ctrl-click every pokemon I would like to transfer and transfer them all in one operation. I dont know if this is possible, well, it's possible, but I dont know how much work it requires :)

Great gui by the way!

**Comment by vandernorth** [comment]
Thanks!

I've added this for evolve and transfer in the next release. It uses the DelayBetweenPlayerActions setting so it depends how long your transfers/evolves will take ;-)

**Comment by vandernorth** [comment]
Fixed in https://github.com/vandernorth/NecroBot.GUI/releases/tag/v0.3.2
