### ISSUE TITLE
Support Multi-Language

### ISSUE THREAD

**Issue by Reg-Li** [vandernorth/NecroBot.GUI#71]
Dear Sir,

Could you implement the multi-language in the newer version?

**Comment by RuneMykle** [comment]
https://github.com/vandernorth/NecroBot.GUI/issues/37

**Comment by LiraGamer** [comment]
I agree ! :+1:

**Comment by vandernorth** [comment]
I will not do it myself, I simply do not have the time. If there are others dev's somewhere in the community, please feel free to contribute.
