### ISSUE TITLE
NecroBot.GUI-0.4.2\PokeGUI.cs line 943 error

### ISSUE THREAD

**Issue by mickeyboss123** [vandernorth/NecroBot.GUI#72]
NecroBot.GUI-0.4.2\PokeGUI.cs line 943 error

**Comment by vandernorth** [comment]
Do you have the error as well?

The line is:
Task task = UseLuckyEggConstantlyTask.Execute(this._session, new CancellationToken());

**Comment by Elenedeath** [comment]
I have this error too, need to edit the file "UseLuckyEggConstantlyTask.cs" found in "PoGo.NecroBot.Logic/Tasks/" and replace "class UseLuckyEggConstantlyTask" to "public class UseLuckyEggConstantlyTask".
After this you can compile without error.
I use this to compile my build, you can check on my repository.

**Comment by mickeyboss123** [comment]
thinks..

**Comment by vandernorth** [comment]
Ah yeah, forgot about that! Sorry guys.
