### ISSUE TITLE
Issue - Pokemon tab

### ISSUE THREAD

**Issue by RuneMykle** [vandernorth/NecroBot.GUI#75]
Pokemon tab can't auto-update as keeping inventory requires some time and it updates each time a new poke is found.
Please make the tab as it was with only updating upon button press "Refresh".

Catches tab is perfect as it is with auto-update.

**Comment by jimmyxXx** [comment]
Just to make sure I understand the issue, you are saying that refreshing the Pokemon tab automatically is bad because it takes too long to refresh? How long does it take to refresh, and how do you know? (I haven't noticed any delays, but perhaps I'm not looking in the right place)?

**Comment by RuneMykle** [comment]
haha, no :) When using most standard configs you get many of certain types of pokemons. (Defined in config). One of the beauties of this gui is that you can control-click several pokemons and batch transfer all the bad ones, leaving just the very best in your bag. 
With the current automatic refresh each time a new pokemon is caught there's no time to figure out the best one and control-click the rest before another pokemon enters the list and resets the marked ones.

Optimally, at least for me, the only way to reset the pokemons tab would be to click the "Refresh" button.

**Comment by jimmyxXx** [comment]
I see.
Perhaps there should be a toggle to turn on/off the auto refresh.
I don't do such batch transfers from this UI, so I like the automatic
refresh.

**Comment by RuneMykle** [comment]
The automatic refresh in the "Catches" tab is perfect and is what most are watching I would assume. Sort it by cp or iv and it's entertaining to watch. But the refresh in the standard pokemon tab isn't very useful as one doesn't see more than a tiny bit of all the pokemons. 

The options when right-clicking on the pokemons is at least not very useful with the auto-refresh.

Then again, if you run a very slow config you wont have this issue at all as it's more than enough time to do most things, but many run configs where pokemons are catched every 5-6 seconds or so which then becomes the time frame to do ones operations and comparement of similar pokemons.

**Comment by vandernorth** [comment]
Yeah I'm gonna have to make some settings where you can turn things like auto-updates off per panel and more...
