### ISSUE TITLE
Stop\Start Button

### ISSUE THREAD

**Issue by nhailong** [vandernorth/NecroBot.GUI#76]
Sometimes, it's usefull to stop the bot for couple minutes to be able to login via real cellphone. This thing shouldn't be to difficult.

**Comment by vandernorth** [comment]
Not as easy as you think as I need to bypass the statemachine in the bot. But it should be do-able. I'll look into it :-)

**Comment by vandernorth** [comment]
Found out this is impossible at the moment.
