### ISSUE TITLE
walk on the real road

### ISSUE THREAD

**Issue by PierceJhuang** [vandernorth/NecroBot.GUI#78]
1. walk on the road or street not to pass through the building or river
2. auto change account by running two or three hours.

thank you, vandernorth~

**Comment by parkpaya** [comment]
Loveee it <3
number 1 req feature is want i try to tell him :)

**Comment by vandernorth** [comment]
1. Thats more something for the real bot-code, or use GPX or #69 
2. #63 

Closing this as a duplicate
