### ISSUE TITLE
eror when openned

### ISSUE THREAD

**Issue by mawmaw2010** [vandernorth/NecroBot.GUI#8]
![eror](https://cloud.githubusercontent.com/assets/20974233/17596029/c527591c-6019-11e6-8689-813ea4396a51.jpg)

hy bro why like this? its bug?how to fix it?

**Comment by vandernorth** [comment]
Its a known problem with the map implementation (http://stackoverflow.com/questions/22285763/json-is-undefined)

You can try the registry settings mentioned over there. I'll try to incorporate those later on as well.

**Comment by vandernorth** [comment]
This is possibly fixed in the latest release. Try opening it with admin privileged once.

see https://github.com/vandernorth/NecroBot.GUI/releases/tag/v0.3.2
