### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by ChenQiuming** [vandernorth/NecroBot.GUI#80]
CS0227	Unsafe code may only appear if compiling with /unsafe	PokemonGo.RocketAPI	E:\NecroBot\feroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs	176	
Metadata file 'E:\NecroBot\feroxRev\PokemonGo.RocketAPI\bin\Debug\Pokemon.Go.Rocket.API.dll' could not be found	PoGo.NecroBot.Logic	E:\NecroBot\PoGo.NecroBot.Logic\CSC
Metadata file 'E:\NecroBot\PoGo.NecroBot.Logic\bin\Debug\PoGo.NecroBot.Logic.dll' could not be found	PoGo.NecroBot.CLI	E:\NecroBot\PoGo.NecroBot.CLI\CSC	1
Metadata file 'E:\NecroBot\feroxRev\PokemonGo.RocketAPI\bin\Debug\Pokemon.Go.Rocket.API.dll' could not be found	PoGo.NecroBot.CLI	E:\NecroBot\PoGo.NecroBot.CLI\CSC	1
Metadata file 'E:\NecroBot\PoGo.NecroBot.CLI\bin\Debug\NecroBot.exe' could not be found	PoGo.NecroBot.GUI	E:\NecroBot\NecroBot.GUI-master\CSC	1
Metadata file 'E:\NecroBot\PoGo.NecroBot.Logic\bin\Debug\PoGo.NecroBot.Logic.dll' could not be found	PoGo.NecroBot.GUI	E:\NecroBot\NecroBot.GUI-master\CSC	1
Metadata file 'E:\NecroBot\feroxRev\PokemonGo.RocketAPI\bin\Debug\Pokemon.Go.Rocket.API.dll' could not be found	PoGo.NecroBot.GUI	E:\NecroBot\NecroBot.GUI-master\CSC	1

**Comment by vandernorth** [comment]
This is not something I can help you with, it doesnt really look like a problem though...
