### ISSUE TITLE
PoGo.NecroBot.GUI,

### ISSUE THREAD

**Issue by ChenQiuming** [vandernorth/NecroBot.GUI#81]
5>E:\NecroBot\NecroBot.GUI\PokeGUI.cs(135,13,135,31): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
5>E:\NecroBot\NecroBot.GUI\PokeGUI.cs(943,37,943,62): error CS0122: 'UseLuckyEggConstantlyTask' is inaccessible due to its protection level
5>E:\NecroBot\NecroBot.GUI\PokeGUI.cs(792,35,792,57): warning CS0649: Field 'PokeGUI.snipeCancellationToken' is never assigned to, and will always have its default value

**Comment by vandernorth** [comment]
Ignoring the warnings leaves us with:
5>E:\NecroBot\NecroBot.GUI\PokeGUI.cs(943,37,943,62): error CS0122: 'UseLuckyEggConstantlyTask' is inaccessible due to its protection level

Which is true, I had to modify the UseLuckyEggConstantlyTask to by public. Hope that helps.
