### ISSUE TITLE
Close button does not work

### ISSUE THREAD

**Issue by tmathura** [vandernorth/NecroBot.GUI#82]
This is a minor bug since you can use the 'X' close button but the close button when you click on the pokeball on the top left does not work, the button that says 'Quit
![2016-08-17_17-06-07](https://cloud.githubusercontent.com/assets/20637791/17741600/150a3a80-649d-11e6-939b-ccf31c84bbcc.jpg)
'

**Comment by vandernorth** [comment]
Removed it...

**Comment by tmathura** [comment]
thanks! :-)
