### ISSUE TITLE
like this  [23:03:57] (Info) Pokemons to evolve = 0 How to edit (Info)

### ISSUE THREAD

**Issue by mickeyboss123** [vandernorth/NecroBot.GUI#83]
like this  [23:03:57] (Info) Pokemons to evolve = 0 How to edit string --> (Info)

**Comment by vandernorth** [comment]
What?

**Comment by mickeyboss123** [comment]
command Strings 
[ xx:xx:xx ]  (  Info  ) ...   or [ xx:xx:xx ]  (  Pokestop  )

**Comment by vandernorth** [comment]
I close this issue as there seems to be no question and/or issue. 
If you think about submitting a new issue, please be as clear as possible and at least ask a question.
