### ISSUE TITLE
Request Function - Moves and keep min operator

### ISSUE THREAD

**Issue by f3l1p1nh07** [vandernorth/NecroBot.GUI#84]
would have put the function MoveandKeepMinOperator?
to function as follows.

example I wanted to stay in the inventory only pokemon with IV = X, Y = LEVEL, and MOVES = X + Y ... however stay with them only if the moves and keep min are = "and" and not if only moves or just mins ...

There is also a command for him not to consider the CP? only the level and IV? and everything that does not have LIGHT IV and configured to transfer?

**Comment by vandernorth** [comment]
This is not GUI related, I cannot help you with this.
