### ISSUE TITLE
add more function as another necrobot did?

### ISSUE THREAD

**Issue by jaschoo1988** [vandernorth/NecroBot.GUI#85]
Just suggest...

UseWalkingSpeedVariant : so the bot will walk with random/hi-low speed
ThrowMissPercentage: so it won't be 100% hit the pokemon, sometimes will miss

**Comment by tmathura** [comment]
@vandernorth just does the GUI, that will be part for the actual necro team dev (not sure if they did implement it). he has a milestone set: https://github.com/vandernorth/NecroBot.GUI/milestone/5 for updating the necro bot for issue: https://github.com/vandernorth/NecroBot.GUI/issues/27 

I'd say this is a duplicate.

**Comment by vandernorth** [comment]
Thanks @tmathura

**Comment by tmathura** [comment]
No problem, just trying to help :-)
