### ISSUE TITLE
Request feature

### ISSUE THREAD

**Issue by hanncreator** [vandernorth/NecroBot.GUI#87]
Hello , whether there will be a feature where we know how much pokestop or pokemon that we can ?

**Comment by vandernorth** [comment]
That we can what?

**Comment by hanncreator** [comment]
how do i know i collect pokemon and take pokestop?

But Pokestop ban:
- Occurs when you search roughly 2k pokestops in a 23 hour timespan.
- No bypasses known.


Pokemon ban:
- Occurs when you catch 1k pokemon in a 23 hour timespan.
- Potential bypass by throwing missing pokeballs 15-30 times. (I haven't confirmed)

**Comment by kevinjew** [comment]
Other suggested
record last GPS location and re-write to config.json "DefaultLatitude" and "DefaultLongitude"
