### ISSUE TITLE
NecroBot V0.9 No listener for event xxxxxxxEvent

### ISSUE THREAD

**Issue by kevinjew** [vandernorth/NecroBot.GUI#88]
I put some NecroBot V0.9.0 file into the Resource folder.
The NecroBot.GUI happen "No listener for event HumanWalkingEvent" message.

The Config.json, I add some "//description" but when I open the program, The description was delete.
I need add some comment in the file for remember function.

**Comment by vandernorth** [comment]
No listener for event HumanWalkingEvent means you haven't implemented one of the new events supplied by 0.9.0.

As per JSON standards you cannot add comments to it. Also on program start, the config is readed, then directly writed out again. So you'll get all new settings that are available.

Anyhow, both not related to the GUI
