### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by f3l1p1nh07** [vandernorth/NecroBot.GUI#89]
1 - Add option to not filter considering the CP only IV and / or level. example: if set CP: 0 (disregarding the CP) only consider the IV / LEVEL.

2 - Add option of operation to analyze whether the Pokemon has the listed moves and minimum requirements example:

   "Snorlax": {
       "KeepMinCp": 6000,
       "KeepMinLvl" 23
       "UseKeepMinLvl": true,
       "KeepMinIvPercentage": 90.0,
       "KeepMinDuplicatePokemon": 3,
       "Moves": [
         [
           "ZenHeadbuttFast"
           "Bodyslam"
         ]
       ]
       "DeprecatedMoves": []
       "KeepMinOperator": "or"
       "MovesOperator": "and"
       "MovesKeepOperator": "and" * NEW FUNCTION *
     }

put a MovesKeepOperator filter = "and" or "or"

if set to "and" the pokemon should contain the listed moves, and cp / iv / level listed otherwise will be transferred, if set to "or" when he has any of the requirements it does not transfer.

**Comment by vandernorth** [comment]
Not something I can do, please post this issue to https://github.com/NoxxDev/NecroBot
