### ISSUE TITLE
Compiling errors last rev

### ISSUE THREAD

**Issue by felipetmartini** [vandernorth/NecroBot.GUI#91]
![image](https://cloud.githubusercontent.com/assets/5881404/17751394/4d92dc54-649d-11e6-9ec9-c790c3d379a3.png)

or without changes 4.6.2 but dont know why say missing if i have this intaled

![image](https://cloud.githubusercontent.com/assets/5881404/17751787/16317dea-649f-11e6-87d2-11e8e5249894.png)

this cant be compiled with .net 4.5.2 ????need to be 4.6.2 thats my only change what is my error?

**Comment by vandernorth** [comment]
Do you have the devlopers kit for 4.6.2?

**Comment by LordDeimos** [comment]
Same error as me and have the developer kit 4.6.2

**Comment by felipetmartini** [comment]
yes i have but send me your link to see if is the same version of devlopers kit 4.6.2

**Comment by LordDeimos** [comment]
There is already the link on the front page of the project (if you scroll down).

**Comment by vandernorth** [comment]
You might how to manually fix some of the reference. I've had problems with the google protobuff as well.

 - Go to references beneath the project it states in the error message
 - Delete the google protobuff
 - Right click references then -> Add reference
 - Get the protobuff from the PokemonGoLibs folder

For the references to the project you have in your solution, delete those and reference the projects instead of the DLL.

**Comment by LordDeimos** [comment]
There is to change all the directory on the csproj since it go after a different directory, for example:

`..\..\packages\GPSOAuthSharp.0.0.5\lib\GPSOAuthSharp.dll`

**Comment by felipetmartini** [comment]
i not understand how fix that can you guys explain better? cause necrobot from noxdev compile fine

**Comment by felipetmartini** [comment]
yes i think you are right all projects referencs are linked too necrobox package folder and not to /pokemongolibs/

**Comment by LordDeimos** [comment]
@vandernorth not really used to git so I tried to made some PR on NoxxDev and some were approved, but i messed around and can't get the API (pending a PR) with the fix for the assemply reference.

That way you could also remove the folder PokemonGoLibs as nuget auto download them (at least for me).
