### ISSUE TITLE
Necrobot Gui Crash Bug

### ISSUE THREAD

**Issue by adninnaim** [vandernorth/NecroBot.GUI#92]
### Issue or feature request?
...Issue

![as4](https://cloud.githubusercontent.com/assets/21089728/17752382/1be87f5e-64fe-11e6-9185-d1d3a6a0d7cf.PNG)

### Other Information
Version: 0.3.5 and 0.4.2
Windows Version: Windows 10 Pro x64

What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): 
Run without a hitch before, i am using 0.3.5 and suddenly its crash. Search for the new bot ui and the same error occurred on 0.4.2

**Comment by vandernorth** [comment]
Interesting, Anything in the logs?

**Comment by adninnaim** [comment]
Nope. Just stating this
Initializing NecroBot logger at time 18/8/2016 4:49:12 AM...

then force close.

**Comment by vandernorth** [comment]
Can you try v0.5.0?

**Comment by TraumFabriK79** [comment]
it happened to me too on banned accounts

**Comment by adninnaim** [comment]
Yes. It seem i cannot log in to account in my phone too. So its realyy perma band. Thank you dev for listening. Im done. lol

**Comment by tr1p0z** [comment]
> Yes. It seem i cannot log in to account in my phone too. So its realyy perma band. Thank you dev for listening. Im done. lol

Welcome to the group!
https://gyazo.com/a163d9b25631ec5530f5c3e8a36c04b3
