### ISSUE TITLE
No listener for event HumanWalkingEvent and No listener for event KillSwitchEvent errors

### ISSUE THREAD

**Issue by Trolha69** [vandernorth/NecroBot.GUI#93]
### Issue or feature request?
No listener for event HumanWalkingEvent and No listener for event KillSwitchEvent spam on the log.

### Expected Behavior
N/A

### Actual Behavior
N/A

### Steps to Reproduce
Config is valid as per the online validator, haven't change anything other than coordinates, and some parameters regarding Pokemon evolution.

### Other Information
Version: 0.5.0
Windows Version: Windows 7 Home Ultimate
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): None, just keeps spaming on the bot log.

**Comment by LiraGamer** [comment]
it happened to me too on banned accounts

**Comment by LiraGamer** [comment]
Me too happened! issuance of this message!
version 0.5.0
Windows 8.1 single language!

**Comment by LiraGamer** [comment]
Please replace the circumference of MaxTravel In Distance Meters on the map!
here in 5.0 no longer appear!

**Comment by LiraGamer** [comment]
Please replace the circumference of MaxTravel In Distance Meters on the map!
here in 5.0 no longer appear!

**Comment by jack2005y** [comment]
@LiraGamer I have the same problem. Please explain how can I replace the circumference of MaxTravel In Distance Meters on the map

**Comment by vandernorth** [comment]
Its not in issue, only a feature from v0.9.0 that is not implemented..

**Comment by LiraGamer** [comment]
@vandernorth So the issue this message should ignore?

@jack2005y sorry it was not quite what I meant.
I really wanted to say that the circumference no longer appear on my map!

**Comment by snap5** [comment]
i'm having the same issue here, we should ignore the two mensages ?
Thanks

**Comment by raymonders** [comment]
@vandernorth is the HumanWalkingEvent the walking speed variant? does the speed variant still work? because on the v.9.0 we see updates for the change in walking speed. With your GUI, does the walking speed still change? Thank you four your work
