### ISSUE TITLE
[Suggestion] Discord

### ISSUE THREAD

**Issue by golgolak** [vandernorth/NecroBot.GUI#95]
In case this community still does not have, would be nice to have one going :)

**Comment by vandernorth** [comment]
Feel free to do something. I don't have time to be on a discord channel ;-)

**Comment by golgolak** [comment]
sure i'd be happy to, hopefully this will lessen issue tickets that are not real issues... 
you can add this link somewhere... 

https://discord.gg/DFTgkaF
