### ISSUE TITLE
Evolving

### ISSUE THREAD

**Issue by mmanlapat** [vandernorth/NecroBot.GUI#96]
### Issue or feature request?
Issue

### Expected Behavior
Evolve pokemon in the "PokemonsToEvolve" in config.json
Not sure if there is a boolean for that but it wont evolve them. 

### Actual Behavior
Not evolving or don't know when to start evolving.

![capture](https://cloud.githubusercontent.com/assets/5326695/17762749/f784d980-6545-11e6-87ef-cf2b69f26768.JPG)

![adsf](https://cloud.githubusercontent.com/assets/5326695/17762856/cfa850c6-6546-11e6-8148-0f3769f95f56.JPG)

### Steps to Reproduce
Run the bot, have a ton of pidgey. Candies piles up with no evolve

### Other Information
Version: 0.5.0
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): evolve

**Comment by vandernorth** [comment]
There are sooo many other settings.. but I guess you have the "EvolveKeptPokemonsAtStorageUsagePercentage" set..... it will wait until your whole pokemon inventory is the amount you set it to, lets say 90% full. 

It does so when KeepPokemonsThatCanEvolve is set to true

**Comment by mmanlapat** [comment]
Im trying to do is: 
using all candies to common pokemon (which are on the list)

and then saving other (like a dratini) in case i caught a good one.rather than use it to evolve a weak one
