### ISSUE TITLE
Cannot open the GUI

### ISSUE THREAD

**Issue by jack2005y** [vandernorth/NecroBot.GUI#97]
### Issue or feature request?
...Issue

### Expected Behavior
...The GUI should be running after I trouble click the .exe

### Actual Behavior
...Nothing happened, nothing pop up

### Steps to Reproduce
...Reinstall windows framework, restart, re-download the program

Still doesn't work

### Other Information
Version: 0.5.0
Windows Version: Windows 10 Home 64 bit

Update: All of them is latest version and GUI replace the auth.json and config.json with its default one every time after I clicked the .exe

**Comment by mmanlapat** [comment]
did you donwload the necro 0.9.0?

**Comment by jack2005y** [comment]
Yes. But it should work just by replacing the auth.json, config.json from necro 0.9.0 right?

**Comment by iamspa** [comment]
Completes this milestone

    Update to NoxxDev's Necrobot v0.9.0 #27 #34
    You're gonna need .NET Framework v4.6.2 to run this
    Backup your config before running, v0.9.0 uses a different, more organized structure.
    Zoomlevel on the map is now according to walkingRadius
    Removed non-functioning close button #82
    Dates are added to logging #58

**Comment by jack2005y** [comment]
@iamspa I do not understand what you mean

**Comment by jack2005y** [comment]
Problem solved

**Comment by vandernorth** [comment]
How did you solve it?
